/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData add_comment_black_24dp_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_photo_alternate_black_24dp_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData auto_graph_black_24dp_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_center_black_24dp_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campaign_black_24dp_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_black_24dp_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_all_black_24dp__1__1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error_black_24dp_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_color_fill_black_24dp_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_black_24dp_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_outline_white_24dp_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_add_black_24dp_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_active_black_24dp_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_black_24dp_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_call_black_24dp_1 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_file = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_italic_24px__1_ = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_account_plus_outline = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_align_horizontal_center = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_align_horizontal_left = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_align_horizontal_right = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_archive_arrow_down_outline = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_arrow_left = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_at = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_bell_outline = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_calendar_outline = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_check = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_checkbox_blank_outline = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_checkbox_marked = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_checkbox_outline = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_clipboard_multiple_outline = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_close = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_cog_outline = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_comment_outline = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_compare_horizontal = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_dots_horizontal = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_dots_vertical = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_eye = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_folder_outline = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_align_center = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_align_left = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_align_right = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_bold = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_font = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_header_1 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_header_2 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_list_bulleted_square = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_list_bulleted = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_list_numbered = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_strikethrough_variant = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_format_underline = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_home_outline = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_image_auto_adjust = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_image_edit_outline = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_image_text = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_link = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_loading = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_magnify_minus_outline = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_magnify_plus_outline = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_magnify = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_menu = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_message_text_outline = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_minus = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_move_resize_variant = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_plus = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_resize_1 = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_resize = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_send = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_square_edit_outline = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_table_edit = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_trash_can_outline = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_tray_arrow_up = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo_24px_2 = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo_24px_2 = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector__2_ = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notif_upload = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_comment_black_24dp_2 = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData board_icon = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_in_icon = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_icon = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_chat_icon = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData overview_icon = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule_icon = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_editteam = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_statistic = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_work_load = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_chat = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
